# Generated by Django 5.1.3 on 2025-01-29 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_critica_cliente_critica_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='mueble_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
